### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by f33r0** [paulhammond/s3simple#7]
Hello. Is the script not working at the moment? can't login to download from s3
Anyway I get 403 error
And how I can download directory?

**Comment by paulhammond** [comment]
Hi! I think the script is working for other people but you haven't really given enough information to be able to give you any help.

s3simple is deliberately very simple and doesn't handle extra features like downloading a directory. I'd suggest using [the AWS CLI](https://aws.amazon.com/cli/) if you want something that downloads a directory.

I'm going to close this issue because I don't know what else to do. If you have more information on your error feel free to reopen it with more details.
